### ISSUE TITLE
Could not install add-on

### ISSUE THREAD

**Issue by john-bodley** [modheader/modheader_selenium#28] opened 2022-02-19 00:34 UTC
@hao1300 we're just started noticing an issue (within the past few hours) with the [firefox-modheader/modheader.xpi](http://github.com/bewisse/modheader_selenium/blob/master/firefox-modheader/modheader.xpi) add-on, specifically we're receiving the following errors:

```
Could not install add-on: /tmp/tmpw048_e__: ERROR_CORRUPT_FILE: The file appears to be corrupt.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5
install@chrome://remote/content/marionette/addon.js:86:13
```

and was wondering whether it was related to your recent https://github.com/modheader/modheader_selenium/commit/efc74ff496320faec275a17b7abf2fc2d22d5538 commit.

**Comment by hao1300** [comment] 2022-02-19 10:47
@john-bodley - that is quite possible. I just released new .xpi file, though it should have been signed and released the same way as before. Can you share some code snippet on how you are loading it? I am not able to reproduce on my side.

**Comment by hao1300** [comment] 2022-02-19 11:03
To be sure, I have republished a new version. Can you give that a try too to see if it is working?

**Comment by hao1300** [comment] 2022-02-25 20:30
Closing this issue. Feel free to reopen with more details if you still run into issues.

**Closed by hao1300** 2022-02-25 20:30 UTC
